// Generated by typings
// Source: https://raw.githubusercontent.com/types/npm-https-proxy-agent/6e0cb6d6cfdeddffb06377c539790b9c501bce9b/index.d.ts
declare module 'https-proxy-agent' {
import { Agent } from 'http';

class HttpsProxyAgent extends Agent {
  constructor (uri: string | { protocol?: string; host?: string; hostname?: string; port?: string });
}

export = HttpsProxyAgent;
}
