// Generated by typings
// Source: https://raw.githubusercontent.com/types/npm-http-proxy-agent/b2cc033f660e62c3a7b8362898b16eefa3ad3939/index.d.ts
declare module 'http-proxy-agent' {
import { Agent } from 'http';

class HttpProxyAgent extends Agent {
  constructor (uri: string | { protocol?: string; host?: string; hostname?: string; port?: string });
}

export = HttpProxyAgent;
}
